Fix runtime panic (zenflow 31840ca7)
Fix the runtime panic.

"thread 'main' (210959351) panicked at library/core/src/panicking.rs:225:5:
attempted to zero-initialize type `gpui::app::entity_map::Entity<components::tree_view::TreeView>`, which is invalid
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting."